### ISSUE TITLE
Improve CLI

### ISSUE THREAD

**Issue by jamesroutley** [rdkr/oniongen-go#1]
Print usage docs when the command is run without arguments.

Currently: 

```shell
$ go run main.go                                                                                                                                             master
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xe5000, 0xc42000a1a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/Users/jamesroutlry/code/go/src/github.com/rdkr/oniongen/main.go:53 +0x15a
exit status 2
```

**Comment by rdkr** [comment]
Thanks! I've updated the readme with usage instructions for now instead, as I'm focussing on reimplementing this project in C at the moment: https://github.com/rdkr/oniongen-c
